#!/usr/bin/env python3
"""v23: Evidence for config-tuning PRs — our re-tuned fused_moe config vs sglang's
stale fallback config, on the exact Qwen3-30B-A3B shape (E=128,N=768,H200).

Reproduces the *mechanism* of the "add tuned fused_moe config for <model> on H200"
class of PRs (#27112, #20565, #18969, ...) on OUR uncovered shape:
- Baseline = the config sglang actually loads today (triton_3_5_1 has no H200 E=128
  config -> falls back to triton_3_2_0/E=128,N=768,H200.json, "sub-optimal" warning).
- Candidate = the config we generated by running sglang's official tuning script on
  triton 3.5.1 for our shape (results/autotune_qwen3_moe/...).
We time the real fused_moe triton kernel under each config (CUDA-graph timed, L2
flushed) and report kernel-time delta = the reproducible perf evidence.
"""
import json, os, sys, argparse
import torch

BENCH_DIR = "/home/t-jialianggu/work/sglang/benchmark/kernels/fused_moe_triton"
sys.path.insert(0, BENCH_DIR)
from tuning_fused_moe_triton import benchmark_config  # noqa: E402
from common_utils import get_model_config  # noqa: E402

torch.set_default_device("cuda")
torch.cuda.manual_seed_all(0)

MODEL = "/data/hf/models/Qwen3-30B-A3B-Instruct-2507"
REPO = "/home/t-jialianggu/work/EndtoEnd-auto-optimization"
FALLBACK = ("/home/t-jialianggu/work/sglang/python/sglang/srt/layers/moe/fused_moe_triton/"
            "configs/triton_3_2_0/E=128,N=768,device_name=NVIDIA_H200.json")
# sglang-dev is an editable install rooted at /home/t-jialianggu/work/sglang
OURS = f"{REPO}/results/autotune_qwen3_moe/E=128,N=768,device_name=NVIDIA_H200.json"

ap = argparse.ArgumentParser()
ap.add_argument("--batches", type=str, default="32")
ap.add_argument("--iters", type=int, default=100)
args = ap.parse_args()

mc = get_model_config(MODEL, tp_size=1)
E = mc["num_experts"]; topk = mc["topk"]; hidden = mc["hidden_size"]
shard = mc["shard_intermediate_size"]; dtype = mc["dtype"]; block_shape = mc["block_shape"]
print(f"shape: E={E} topk={topk} hidden={hidden} shard_intermediate={shard} dtype={dtype} block_shape={block_shape}", flush=True)

fb_all = json.load(open(FALLBACK))
ours_all = json.load(open(OURS))

def default_heuristic(M):
    # bf16 branch of get_default_config (fused_moe_triton_config.py)
    if M <= E:
        return {"BLOCK_SIZE_M": 16, "BLOCK_SIZE_N": 32, "BLOCK_SIZE_K": 64, "GROUP_SIZE_M": 1}
    return {"BLOCK_SIZE_M": 64, "BLOCK_SIZE_N": 64, "BLOCK_SIZE_K": 32, "GROUP_SIZE_M": 8}


def bench(cfg, M):
    return benchmark_config(cfg, M, E, shard, hidden, topk, dtype,
                            use_fp8_w8a8=False, use_int8_w8a8=False,
                            use_int8_w8a16=False, per_channel_quant=False,
                            block_shape=block_shape, num_iters=args.iters)

rows = []
print(f"\n{'batch':>6}{'default_us':>12}{'fallback_us':>13}{'ours_us':>10}{'tuned/default':>15}", flush=True)
for b in [int(x) for x in args.batches.split(",")]:
    key = str(b)
    t_d = bench(default_heuristic(b), b)
    t_fb = bench(fb_all[key], b) if key in fb_all else None
    t_our = bench(ours_all[key], b) if key in ours_all else None
    best_tuned = min([t for t in [t_fb, t_our] if t is not None], default=None)
    sp = (t_d / best_tuned) if best_tuned else None
    rows.append({"batch": b, "default_us": round(t_d, 2),
                 "fallback_us": round(t_fb, 2) if t_fb else None,
                 "ours_us": round(t_our, 2) if t_our else None,
                 "tuned_over_default": round(sp, 4) if sp else None})
    fbs = f"{t_fb:>13.2f}" if t_fb else f"{'-':>13}"
    ourss = f"{t_our:>10.2f}" if t_our else f"{'-':>10}"
    sps = f"{sp:>14.3f}x" if sp else f"{'-':>15}"
    print(f"{b:>6}{t_d:>12.2f}{fbs}{ourss}{sps}", flush=True)

out = f"{REPO}/results/2026-07-19_v23_config_evidence"
os.makedirs(out, exist_ok=True)
json.dump({"model": MODEL, "shape": {"E": E, "shard_N": shard, "hidden": hidden, "topk": topk},
           "note": "tuned_over_default = kernel speedup of best tuned config vs default heuristic",
           "results": rows}, open(f"{out}/fused_moe_config_speedup.json", "w"), indent=2)
print(f"\nwrote {out}/fused_moe_config_speedup.json")
